version: '3'
services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      # source:target
      - ./volumes/static_collection:/var/shit/static_collection/
      - ./volumes/data/:/var/shit/data/
      - ./volumes/media/images/:/var/shit/media/images/
      - ./volumes/media/portraits/:/var/shit/media/portraits/
      - ./volumes/private_settings.py:/var/shit/shit/private_settings.py
    ports:
      - "127.0.0.1:8000:8000"
