# Generated by Django 3.1.2 on 2020-10-27 19:17

import blog.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('pgp_public_key', models.TextField(blank=True, null=True, verbose_name='Öffentlicher PGP-Schlüssel')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autoren',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Freilassen, um Slug aus dem Titel zu generieren', max_length=255, null=True, unique=True)),
            ],
            bases=(blog.models.Sluggable, models.Model),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('slug', models.SlugField(blank=True, help_text='Freilassen, um Slug aus dem Titel zu generieren', max_length=255, null=True, unique=True)),
                ('content', models.TextField(help_text='Unterstützt Markdown-Syntax', verbose_name='Inhalt')),
                ('published', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Veröffentlicht am')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('authors', models.ManyToManyField(blank=True, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Autoren')),
                ('site', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
            },
            bases=(blog.models.Sluggable, models.Model),
        ),
    ]
