# Generated by Django 3.1.2 on 2020-10-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, help_text='Unterstützt Markdown-Syntax', null=True, verbose_name='biography'),
        ),
    ]
