# Generated by Django 3.1.2 on 2020-11-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('publish_draft', 'Can publish draft'),), 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
    ]
