# Generated by Django 3.1.2 on 2020-11-01 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201101_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Unterstützt Markdown-Syntax', verbose_name='Inhalt')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('accepted', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Angenommen am')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='Artikel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
