# Generated by Django 3.1.2 on 2020-11-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201102_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to='images', verbose_name='Bild', width_field='width'),
        ),
    ]
