# Generated by Django 3.1.2 on 2020-11-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201102_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pixel', null=True, verbose_name='Höhe'),
        ),
        migrations.AddField(
            model_name='author',
            name='portrait',
            field=models.ImageField(blank=True, height_field='height', max_length=255, null=True, upload_to='portrait', verbose_name='Portait', width_field='width'),
        ),
        migrations.AddField(
            model_name='author',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pixel', null=True, verbose_name='Breite'),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pixel', null=True, verbose_name='Höhe'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pixel', null=True, verbose_name='Breite'),
        ),
    ]
